networks:
  ingest-network:
    name: ingest-network
    driver: bridge

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U temporal" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - ingest-network

  temporal:
    image: temporalio/auto-setup:latest
    container_name: lore-ingestor-temporal
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_SEEDS: postgres
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_DB: temporal
      # DYNAMIC_CONFIG_FILE_PATH can be set later when you have a file
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7233:7233"
    networks:
      - ingest-network

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      TEMPORAL_ADDRESS: lore-ingestor-temporal:7233
    ports:
      - "8233:8080"
    depends_on:
      - temporal
    networks:
      - ingest-network

  temporal-worker:
    build: .
    container_name: lore-ingestor-temporal-worker
    command: [ "python", "-m", "service.wait_for_temporal" ]
    restart: unless-stopped
    environment:
      DB_PATH: /app/data/tropes.db
      TEMPORAL_TARGET: "lore-ingestor-temporal:7233"
      TEMPORAL_NAMESPACE: "default"
      TEMPORAL_TASK_QUEUE: "ingest-queue"
      # optional wait knobs:
      # WAITER_ATTEMPTS: "90"
      # WAITER_SLEEP_SECONDS: "2"
    volumes:
      - ./lore_ingest:/app/lore_ingest:ro
      - ./service:/app/service:ro
      - ./cli:/app/cli:ro
      - ./data:/app/data
    depends_on:
      - temporal
    networks:
      - ingest-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - ingest-network

  nats:
    image: nats:2
    command: [ "-js" ]
    ports:
      - "4222:4222"
    networks:
      - ingest-network

  pushgateway:
    image: prom/pushgateway:v1.7.0
    command: [ "--web.listen-address=:9091" ]
    ports:
      - "9091:9091"
    networks:
      - ingest-network

  http:
    build: .
    container_name: lore-ingestor-http
    command: [ "uvicorn", "service.http_app:app", "--host", "0.0.0.0", "--port", "8099" ]
    environment:
      DB_PATH: /app/data/tropes.db
      INBOX: /app/inbox
      SUCCESS_DIR: /app/success
      FAIL_DIR: /app/fail
      EMIT_SINK: "stdout,redis,nats"
      EMIT_HTTP_URL: "http://host.docker.internal:9000/webhook"
      EMIT_REDIS_URL: "redis://redis:6379/0"
      EMIT_REDIS_LIST: "ingest_events"
      EMIT_NATS_URL: "nats://nats:4222"
      EMIT_NATS_SUBJECT: "ingest.events"
      PUSHGATEWAY_URL: "http://pushgateway:9091"
      PUSHGATEWAY_JOB: "lore-ingest-http"
      PUSHGATEWAY_INSTANCE: "${HOSTNAME:-lore-ingestor-http}"
      PUSHGATEWAY_MODE: "pushadd"
      TEMPORAL_ENABLED: "true"
      TEMPORAL_TARGET: "lore-ingestor-temporal:7233"
      TEMPORAL_NAMESPACE: "default"
      TEMPORAL_TASK_QUEUE: "ingest-queue"
    volumes:
      - ./lore_ingest:/app/lore_ingest:ro
      - ./service:/app/service:ro
      - ./cli:/app/cli:ro
      - ./data:/app/data
      - ./inbox:/app/inbox
      - ./success:/app/success
      - ./fail:/app/fail
    ports:
      - "8099:8099"
    depends_on:
      - temporal
      - temporal-worker
      - redis
      - nats
    restart: unless-stopped
    networks:
      - ingest-network

  watcher:
    build: .
    container_name: lore-ingestor-watcher
    command: [ "python", "-m", "cli.main", "watch" ]
    environment:
      DB_PATH: /app/data/tropes.db
      INBOX: /app/inbox
      SUCCESS_DIR: /app/success
      FAIL_DIR: /app/fail
      ALLOWED_EXT: ".txt,.md,.pdf,.docx"
      MAX_FILE_MB: "20"
      INGEST_PROFILE: "pdf_pages"
      EMIT_SINK: "stdout,redis,nats"
      EMIT_HTTP_URL: "http://host.docker.internal:9000/webhook"
      EMIT_REDIS_URL: "redis://redis:6379/0"
      EMIT_REDIS_LIST: "ingest_events"
      EMIT_NATS_URL: "nats://nats:4222"
      EMIT_NATS_SUBJECT: "ingest.events"
      PUSHGATEWAY_URL: "http://pushgateway:9091"
      PUSHGATEWAY_JOB: "lore-ingest-watcher"
      PUSHGATEWAY_INSTANCE: "${HOSTNAME:-lore-ingestor-watcher}"
    volumes:
      - ./lore_ingest:/app/lore_ingest:ro
      - ./service:/app/service:ro
      - ./cli:/app/cli:ro
      - ./data:/app/data
      - ./inbox:/app/inbox
      - ./success:/app/success
      - ./fail:/app/fail
    depends_on:
      - http
      - redis
      - nats
    restart: unless-stopped
    networks:
      - ingest-network
